=== nsvir/FAC_2015_2016/NAW/TP1/exo1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT formules (constantes,exps)>
<!ELEMENT constantes (const)+>
<!ELEMENT const EMPTY>
<!ELEMENT exps (exp)+>
<!ELEMENT exp (op|var)>
<!ELEMENT op ((op|var),(op|var))>
<!ELEMENT var EMPTY>
<!ATTLIST const nom ID #REQUIRED valeur CDATA #REQUIRED>
<!ATTLIST exp nom CDATA #REQUIRED>
<!ATTLIST op symbole (plus|moins|mult|div) #REQUIRED>
<!ATTLIST var nom IDREF #REQUIRED>

=== nsvir/FAC_2015_2016/NAW/TP1/exo1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE formules SYSTEM "exo1.dtd">
<formules>
	<constantes>
		<const nom="A" valeur="1"/>
		<const nom="B" valeur="7"/>
		<const nom="C" valeur="50"/>
	</constantes>
	<exps>
		<exp nom="exp1">
			<op symbole="mult">
				<op symbole="plus">
					<var nom="A"/>
					<var nom="B"/>
				</op>
				<op symbole="moins">
					<var nom="A"/>
					<var nom="B"/>
				</op>
			</op>
		</exp>
		<exp nom="exp2">
			<op symbole="mult">
				<op symbole="moins">
					<op symbole="moins">
						<var nom="A"/>
						<var nom="B"/>
					</op>
					<var nom="C"/>
				</op>
				<var nom="A"/>
			</op>
		</exp>
		<exp nom="exp3">
			<op symbole="mult">
				<var nom="C"/>
				<op symbole="mult">
					<op symbole="div">
						<var nom="A"/>
						<var nom="B"/>
					</op>
					<var nom="C"/>
				</op>
			</op>
		</exp>
	</exps>
</formules>
