=== nsvir/FAC_2015_2016/NAW/TP4/citation_auteurs.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT citations_auteurs (auteur*)>
<!ELEMENT auteur (texte*)>
<!ATTLIST auteur nom CDATA #REQUIRED>
<!ELEMENT texte (#PCDATA)>

=== nsvir/FAC_2015_2016/NAW/TP4/citation_auteurs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE citations_auteurs SYSTEM "citation_auteurs.dtd">
<citations_auteurs>
	<auteur nom="Paul Nizan">
		<texte>J'avais vingt ans. Je ne laisserai personne dire que c'est le plus bel âge de la vie</texte>
		<texte>l n'y a qu'une espèce valide de voyages, qui est la marche vers les hommes.</texte>
		<texte>Il connaît le prix de la liberté. Il sait déjà que tout se paie, le repos par la peine, la liberté par les coups, l'amour par l'ennui et la vie par la mort.</texte>
	</auteur>
	<auteur nom="Pierre Bourdieu">
		<texte>Dans beaucoup de choix de la vie, il est difficile de savoir la part de la réaction contre et de l'inclination pour.</texte>
	</auteur>
	<auteur nom="Raymond Aron">
		<texte>Ce sont les hommes qui écrivent l'histoire, mais ils ne savent pas l'histoire qu'ils écrivent.
</texte>
	</auteur>
	<auteur nom="Jean Baudrillard">
		<texte> L'eau en poudre : il suffit de rajouter de l'eau pour obtenir de l'eau.</texte>
	</auteur>
	<auteur nom="Ludwig van Beethoven"/>
	<auteur nom="Honoré de Balzac">
		<texte>La gloire est le soleil des morts.</texte>
	</auteur>
	<auteur nom="Léon Tolstoï">
		<texte>La charité du pauvre est de ne pas haïr le riche. </texte>
	</auteur>
	<auteur nom="Jean Paulhan">
		<texte>Il est de la nature de l’évidence qu’elle passe inaperçue. </texte>
	</auteur>
	<auteur nom="Hannah Arendt"/>
	<auteur nom="Talleyrand">
		<texte>On connaît, dans les grandes cours, un autre moyen de se grandir : c’est de se courber. </texte>
		<texte>La politique ce n'est qu'une certaine façon d'agiter le peuple avant de s'en servir. </texte>
		<texte>Les financiers ne font bien leurs affaires que lorsque l'État les fait mal.</texte>
	</auteur>
	<auteur nom="Christian Bobin">
		<texte>Ce qu'on sait de quelqu'un empêche de le connaître.</texte>
		<texte>Les enfants, ce n'est pas sorcier, ça pousse à travers nos erreurs. </texte>
		<texte>Les enfants sont comme les marins : où que se portent leurs yeux, partout c'est l'immense.</texte>
	</auteur>
	<auteur nom="Miguel de Cervantès">
		<texte> La plume est la langue de l’âme. </texte>
	</auteur>
	<auteur nom="Cioran">
		<texte> Se méfier des penseurs dont l'esprit ne fonctionne qu'à partir d'une citation. </texte>
		<texte>Tous les penseurs sont des ratés de l'action et qui se vengent de leur échec par l'entremise des concepts.</texte>
	</auteur>
	<auteur nom="Henri Michaud">
		<texte>Si un contemplatif se jette à l’eau, il n’essaiera pas de nager, il essaiera d’abord de comprendre l’eau. Et il se noiera. </texte>
		<texte>Qui laisse une trace, laisse une plaie.</texte>
		<texte>L'enseignement de l'araignée n'est pas pour la mouche.  </texte>
	</auteur>
	<auteur nom="Henri Bergson">
		<texte>Il faut agir en homme de pensée et penser en homme d'action</texte>
		<texte>L'art de l'écrivain consiste surtout à nous faire oublier qu'il emploie des mots.
</texte>
		<texte>Notre esprit a une irrésistible tendance à considérer comme plus claire l'idée qui lui sert le plus souvent. </texte>
	</auteur>
	<auteur nom="François René de Chateaubriand">
		<texte>Il y a des temps où l’on ne doit dépenser le mépris qu’avec économie, à cause du grand nombre de nécessiteux.
</texte>
		<texte> Les institutions passent par trois périodes : celle des services, celle des privilèges, celle des abus.</texte>
		<texte>Les forêts précèdent les peuples, les déserts les suivent.</texte>
		<texte> L'homme n'a pas besoin de voyager pour s'agrandir ; il porte avec lui l'immensité.</texte>
		<texte>En ce temps-là, la vieillesse était une dignité ; aujourd'hui, elle est une charge. </texte>
		<texte> Le ciel fait rarement naître ensemble l’homme qui veut et l’homme qui peut. </texte>
	</auteur>
	<auteur nom="Gaston Bachelard">
		<texte> Imaginer, c'est hausser le réel d'un ton.</texte>
		<texte>Celui qui trouve sans chercher est celui qui a longtemps cherché sans trouver.</texte>
		<texte> Il faut que l'imagination prenne trop pour que la pensée ait assez. </texte>
	</auteur>
	<auteur nom="Anatole France">
		<texte>La jeunesse a cela de beau qu’elle peut admirer sans comprendre. </texte>
		<texte> Les hommes le plus souvent se querellent pour des mots. C'est pour des mots qu'ils tuent et se font tuer le plus volontiers.</texte>
	</auteur>
	<auteur nom="Albert Guinon">
		<texte>Le contact de la femme est délicieux, et sa présence insupportable.</texte>
		<texte>Les passionnés soulèvent le monde, et les sceptiques le laissent retomber.</texte>
	</auteur>
	<auteur nom="Amélie Nothomb">
		<texte>Les théories servent à irriter les philistins, à séduire les esthètes et à faire rire les autres.</texte>
		<texte>Il y aura toujours dans la foule un crétin qui, sous prétexte qu'il ne comprend pas, décrétera qu'il n'y a rien à comprendre.</texte>
	</auteur>
	<auteur nom="Henri Lacordaire">
		<texte>Entre le passé où sont nos souvenirs et l’avenir où sont nos espérances, il y a le présent où sont nos devoirs.
</texte>
		<texte>Entre le fort et le faible, entre le riche et le pauvre, entre le maître et le serviteur, c'est la liberté qui opprime et la loi qui affranchit.</texte>
	</auteur>
	<auteur nom="Marcel Achard">
		<texte>L'espérance est un de ces remèdes qui ne guérissent pas mais qui permettent de souffrir plus longtemps.
</texte>
		<texte>Le bonheur, c'est la somme de tous les malheurs qu'on n'a pas.</texte>
		<texte>J’ai des tas d’idées brillantes et nouvelles, mais les brillantes ne sont pas nouvelles, et les nouvelles ne sont pas brillantes.
</texte>
		<texte>Il est plus facile de sortir de ses gonds que d'y rentrer. </texte>
	</auteur>
	<auteur nom="Madame de Sévigné">
		<texte>Les femmes ont permission d’être faibles, et elles se servent sans scrupule de ce privilège.
</texte>
		<texte>Gare à la flatterie, ma fille : trop de sucre gâte les dents.</texte>
		<texte>Le coeur n'a pas de rides.</texte>
	</auteur>
	<auteur nom="Alexis de Tocqueville">
		<texte>En politique, la communauté des haines fait presque toujours le fond des amitiés.</texte>
	</auteur>
	<auteur nom="Léon Bloy">
		<texte>On devrait fonder une chaire pour l'enseignement de la lecture entre les lignes.</texte>
	</auteur>
	<auteur nom="Léon Gambetta">
		<texte>Pour gouverner les Français, il faut des paroles violentes et des actes modérés.</texte>
	</auteur>
	<auteur nom="Jacques Prévert">
		<texte>La meilleure façon de ne pas avancer est de suivre une idée fixe.</texte>
		<texte>La meilleure façon de ne pas avancer est de suivre une idée fixe.</texte>
	</auteur>
	<auteur nom="Guy de Maupassant">
		<texte>L'oeil... Tout l'univers est en lui, puisqu'il voit, puisqu'il reflète.</texte>
	</auteur>
	<auteur nom="Voltaire">
		<texte>Les Incas avaient des palais incrustés d'or et couverts de paille : emblème de bien des gouvernements.</texte>
		<texte>Le doute est un hommage que l'on rend à la vérité.</texte>
		<texte>Le prudent se fait du bien, le vertueux en fait aux autres.</texte>
		<texte>La beauté n'est qu'un piège tendu par la nature à la raison.</texte>
		<texte>On aime mieux son égal que son maître.</texte>
		<texte>Pour la plupart des hommes, se corriger consiste à changer de défauts.</texte>
		<texte>Que conclure à la fin de tous mes longs propos ? C'est que les préjugés sont la raison des sots.</texte>
	</auteur>
	<auteur nom="Louis Aragon">
		<texte>Le propre du génie est de fournir des idées aux crétins une vingtaine d'années plus tard.</texte>
	</auteur>
	<auteur nom="Frédéric Dard">
		<texte>La plupart des ménages sont composés de célibataires mariés.</texte>
	</auteur>
	<auteur nom="Georges Clemenceau">
		<texte>On ne ment jamais tant qu'avant les élections, pendant la guerre et après la chasse.
</texte>
		<texte>Les fonctionnaires sont les meilleurs maris : quand ils rentrent le soir à la maison, ils ne sont pas fatigués et ont déjà lu le journal.
</texte>
		<texte>Les femmes vivent plus longtemps que les hommes, surtout quand elles sont veuves.</texte>
		<texte>Pour prendre une décision, il faut être un nombre impair de personnes, et trois c'est déjà trop.
</texte>
		<texte>La démocratie, c'est le pouvoir pour les poux de manger les lions.</texte>
	</auteur>
	<auteur nom="Tristan Bernard">
		<texte>Etre bête présente cet avantage que soi-même on ne s'en aperçoit pas.</texte>
	</auteur>
	<auteur nom="Alphonse de Lamartine">
		<texte> Ignorant d’où je viens, incertain où je vais.</texte>
	</auteur>
	<auteur nom="Raymond Queneau">
		<texte> Il y des gens qui trouvent toujours quelque chose à ne rien dire.</texte>
	</auteur>
	<auteur nom="Pierre-Augustin Caron Beaumarchais">
		<texte>Sans la liberté de blâmer, il n’est point d’éloge flatteur.</texte>
		<texte>Dans le vaste champ de l'intrigue, il faut savoir tout cultiver, jusqu'à la vanité d'un sot.</texte>
		<texte>Dans le vaste champ de l'intrigue, il faut savoir tout cultiver, jusqu'à la vanité d'un sot.</texte>
	</auteur>
	<auteur nom="Alfred Capus">
		<texte>Certains hommes parlent pendant leur sommeil. Il n'y a guère que les conférenciers pour parler pendant le sommeil des autres.</texte>
		<texte> Les mots sont comme les sacs : ils prennent la forme de ce qu'on met dedans.</texte>
		<texte>L’expérience, c’est la forme la plus maussade de la fatigue.</texte>
	</auteur>
	<auteur nom="Herbert Hoover">
		<texte>Bénis soient les plus jeunes, car ils hériteront du déficit budgétaire de l’Etat.</texte>
	</auteur>
	<auteur nom="Pierre Waldeck-Rousseau">
		<texte>Gouverner, c’est choisir entre deux inconvénients.</texte>
	</auteur>
	<auteur nom="Edgar Allan Poe">
		<texte>L'ignorance est une bénédiction, mais pour que la bénédiction soit complète l'ignorance doit être si profonde, qu'elle ne se soupçonne pas soi-même.</texte>
	</auteur>
	<auteur nom="Mark Twain">
		<texte>Consommée avec modération, l'eau ne peut pas faire de mal.</texte>
		<texte>Je n'aime pas l'idée d'avoir à choisir entre le ciel et l'enfer : j'ai des amis dans les deux.</texte>
